# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d01f53899780b9b95b533ffdd993c58b9e4622da777930a22ac99a3fcae5c26abb63bafa0b9129dbfc2720576cf7cfc5cee12ff96cd274008a58602a2dfef722

test:
  secret_key_base: 05e772036d7fb776984fcd3006f0d10ef64f6164c916d6fbb2dd020f94e80645a96195c2362c5c1d489a2b49f4e80f7cbcca7c3df76238f6b4925a9b0e7d8125

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
